apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo-runner
spec:
  data:
  - remoteRef:
      key: forgejo-runner-secret
    secretKey: RUNNER_SECRET
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: forgejo-runner-secret