apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
        - name: ejbca
          image: keyfactor/ejbca-ce:9.3.7
          envFrom:
            - secretRef:
                name: ejbca-container-env
          ports:
            - containerPort: 8080
            - containerPort: 443
