apiVersion: v1
kind: Secret
metadata:
    name: ritregistratie-secrets
    namespace: ritregistratie
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:K7AG7awi9woCjZkOqZpJHq6UXp34toNhZJ4hGvgGuKH0+hu1MFdtmg4Tggv0UN5Xw+MIoQfAywnODRHMsP+NNd8UUn9iQaQDwjpojiudr4E9ktJ1P5Wp0Q==,iv://KdYR/4byoKo8FUcNXr5phnVGq5hxaEY1QtANPBRR8=,tag:uxIukXeCgC5GDsPw0iQ4iQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:6yYb0b0=,iv:kHpqSBIRL31q8WsExt1SUxAerDsfuC4VFcu7yZWmJHg=,tag:1ZpChG/KCiXLErfmxD4ONQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:/iVn0oJdaGwoHVoPf4U=,iv:+Axa8PhoMBuQKf/HzOD4akVsdjFU8D9DMZ9iYfz1jfc=,tag:YOGn3JlHePho7ETiYMOQ5A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:9cdZiw9WdBtaE8zi85aAMw==,iv:RiUgiH00yowad5I6iFLnXoa5nBUDoYWU1lsPwPInizI=,tag:WlPge8VmUR4XJaVW5dczig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMEMrVVdnNWwyMmVQT2hl
            TVVGczRPS3gzK0Nlby94V09rKzhGLytjaEVRCktFSDhQSm1wbGFJRTJCbW9FMll5
            UGtqNGhjZnNmQmRiLzh0VzZ4NXVjNUUKLS0tIDNucHJXdmRSOFJOVWRGbTVSVkUw
            QlpiUG9MaHRxdlpVSHZaOXZ0L1lXTDAKMEZqFE7NT41kQaUJ2s+a2jjdkDGrpcTL
            gaoRZ+Yc/P0a5tTmjG8Jbwcbg0BasVsq0ZZ7SWx9vLeKAPbLfgcpLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T15:18:44Z"
    mac: ENC[AES256_GCM,data:D2vjr/Q1Tn14xBd39y+QDms9QjRbHUeyhP9LeKGvsI1cfdYoSDuiYh+LTWhGv5OAmWhxXzUDNX/hj8x+YIgV3WoGjM+vgC6eH76JYTjRi/Yj5ZenqTs+z0qGrQ5ZaCa9J4GFXipgyluopQg6j9rSVgbH+ogWgF6bsumCwCrZenI=,iv:FzYb9mYm7dY+ggCRvZ/CdkpUJw6kaxZkNeBdPuA9VEQ=,tag:6oQjowft9l3LqNmoig+Jmw==,type:str]
    version: 3.13.3
