apiVersion: v1
kind: ConfigMap
metadata:
  name: garmin-fetch-data-config
  namespace: garmin-grafana
data:
  INFLUXDB_HOST: "influxdb.influxdb.svc.cluster.local"
  INFLUXDB_PORT: "8086"
  INFLUXDB_DATABASE: "GarminStats"
  GARMINCONNECT_IS_CN: "False"
