apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - garmin-fetch-data-configmap.yaml
  - garmin-fetch-data-storage.yaml
  - garmin-fetch-data-deployment.yaml
  - grafana-dashboard-configmap.yaml
