apiVersion: v1
data:
    RUNNER_TOKEN: ENC[AES256_GCM,data:BruVusIOdChAof0oj0JcJPPP2lUumORxAF9sALZbncUxnFNSDBynVGNa2x7yCF7J48gAvYD+DtA=,iv:kPFmaQwdF1hCwjE/GMcubiduUSWaEuU5uSK7NPf2jYU=,tag:fpbCpas/gD7vatJz/m45NQ==,type:str]
    RUNNER_UUID: ENC[AES256_GCM,data:nKIValNCixFPxf2NWaLR1Q1A8UU6HH/Ibwq5To+NUpSD8oGtizOp5W+16Zp4I9yw,iv:uPoffS4OfXg1j++B4dFnG5DHABuHkfQ8JbQLYuSVBKQ=,tag:8WkS/1IxHWghk90dtBp77Q==,type:str]
kind: Secret
metadata:
    name: forgejo-runner-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcTUwNklVcGFod0xyekV0
            RlFCQ2JtT3krVVNDd3FKODViL2R0TGtRbVI4CkgxMjlYSFBBNWdyZUUwUmQvMkQ3
            T2hDcFZZdnk5UVhYVEVWR1g2VmMzc3cKLS0tIDdtdlozblFqQnRGS0h0VnFGdHBu
            TEtMb3pTMnlSOFBTcDZtc2phNDR3aWMK8TEujxfHy6pkWSf5HoJfw8HHeqXAnVev
            xW043hzvL22TEBsDU0YickeZXDo17/ud3AaM6/fsJ9P5QceqPV4WXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T14:59:28Z"
    mac: ENC[AES256_GCM,data:KWPSb21sQvRRJawdqwE1RkHDTLIzTleWD5EY/pbTyDbJEPxAtHSp7fxvVV4gmZKbNHrHN8XWhTe5NoB2QiWx22JlZ8al4nJnMr0rE1xvIUPPInIdUgXceMQV055k26ItzdkMRVFDvkkgflJ+wLLGhU24DWkWQ4C0LFrckXf+dbQ=,iv:Y0u/2twtZy9JPIQpPCh2cpdF57TCHNF3FUPzapWeXvE=,tag:jz5B3Q1ofI8B+n13mnRznA==,type:str]
    version: 3.13.3
