apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallos
  template:
    metadata:
      labels:
        app: wallos
    spec:
      containers:
        - name: wallos
          image: ghcr.io/ellite/wallos:5.4.2
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wallos-storage
              mountPath: /app/storage

      volumes:
        - name: wallos-storage
          persistentVolumeClaim:
            claimName: wallos-storage

