apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.19.3
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          ports:
            - containerPort: 3005
              protocol: TCP

          volumeMounts:
            - name: audiobookshelf-storage
              mountPath: /audiobooks
              subPath: audiobooks
            - name: audiobookshelf-storage
              mountPath: /podcasts
              subPath: podcasts
            - name: audiobookshelf-storage
              mountPath: /config
              subPath: config
            - name: audiobookshelf-storage
              mountPath: /metadata
              subPath: metadata

      volumes:
        - name: audiobookshelf-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-storage
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
      