apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.18.1
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 13378
          volumeMounts:
            - name: audiobookshelf-storage
              mountPath: /audiobooks
              subPath: audiobooks
            - name: audiobookshelf-storage
              mountPath: /podcasts
              subPath: podcasts
            - name: audiobookshelf-storage
              mountPath: /config
              subPath: config
            - name: audiobookshelf-storage
              mountPath: /metadata
              subPath: metadata
      volumes:
        - name: audiobookshelf-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-storage
      securityContext:
        fsGroup: 1000 # node group ID
        runAsUser: 1000 # node user ID
        runAsGroup: 1000 # node group ID
      envFrom:
            - configMapRef:
                name: audiobookshelf-config