apiVersion: v1
data:
    POSTGRES_CONNECTION: ENC[AES256_GCM,data:thBiYJGRPSdBvIpHUbUEy3svyG5h2G77rScbHMX9sv2qO6eFYYwAQoEcj4DEY8mnJOM9RS8ZEG6uaR73CNVk10NuO0iI2g8LZpqk+8vZ369y4CkAi4KgTRZiTbn8E+l0MGzjeqZf1wXDZNCTCVcGI8khOlWrRdrkckAl09cfXrY+zxI5,iv:b2JXY2HfPJs3CAcL5EVMMJY6mHdAWc3fncIA1s4T1VY=,tag:O0dyt/ag9gqNNwppdFW7RA==,type:str]
    UserNameHash: ENC[AES256_GCM,data:SN6XajueKp8Z8PLRUO97L/D7Fm2OtsV7wa9WTytXVneCDlMZ5RpkKMFyHTEoArt2nFophssOLXZhRjsNfi3I9nyHCOklPDF1bVrziYcDE4dYLQXq/cHSOw==,iv:5UoNpOQWojpeZgzbl2JlvO2cs9k31iQ+5RfINE4A1ao=,tag:jOfaHXgAbT5WzL5YWqlemQ==,type:str]
    UserPasswordHash: ENC[AES256_GCM,data:Gm2WwHN3SgQM1vdpaR05YyR5iznC7/efLaVtNKcdnbeO0UFEdHtH0Ktb9vvj9X+/Dq/h4IDoSufe0ipSZrqsCNwozyjZoWb762SEpERnkAo3Ic8zRq+mqA==,iv:dtGDfYGBzhctXcuhi9daCr6x0kSTTL7zZ9/tkELUqn0=,tag:fs3I7mWmAmkfTsWGdKCOig==,type:str]
kind: Secret
metadata:
    name: lubelogger-container-env
sops:
    age:
        - recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTdUUU1qdm9na3VXMjlj
            TVpPNHBSOTlVM2hwRCsrTnhJWHhraC9ZN2dVCitPLzlMUnNxOWVZS282dHVPQmpP
            UkdzYUlDU3FiMFhBeDZ3eXcwMXl5MWsKLS0tIHh3bklsVXRsOVkyeVY3ZS9tYTla
            S2ZycmREckVPLzRKNnVEWU1BM3dPcjgKJ9owBPoP+p70Vmg1RN87Dms4KskSwozD
            kVEw1Ea+kASiFybvDo38y6O9XFuFw1SrbGFEt4E+LBv/rcS6o4rXxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T10:19:29Z"
    mac: ENC[AES256_GCM,data:vTADuYrkUqnz3qkjWWzfg2hroYKu62eQ5jjP7CX2nwnDttOy8ICupa1rNPk1NkXgCLKC2r05KmE3/XPxbqXrRshpiZ0uCY78gS6kDMIMfdQAweRGXk4qQXub/KZ7m/hRGJvC5W5I9YDyxbCj81aNlBnH5VGieMIwijcQizjUy+c=,iv:f4NH+afki3TO5o9QPoGR2ku6KGqDiJq0zlU0N/A1NUs=,tag:tv3gKgF7wyaPPPU2suoKKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
