apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:xuBWuDWioUB51B3/NRxImf8wT5hOy5bIXB9yw/b009xUL22OtTOP5xTufsU/eMCkNaF7sGIETmJUM+5shQikZCuegrR2jx8eyaeslC7u5+elOkQP8AMOPx8OPbcqWczz2deb7m/EqTpbjb+acgJCURrccCOvklNSdrEa5qv0dTvyQMjQU2Qvyha3yVBm1pLM9aa27pN4vpRaCPHqd4bHbG/jiSTCIQ5dP/WWg0xKRWQEd/4T96/pI/AbCRmvW52ox7zA0QgFSRiT4kwsI5NgMBehE0aiWG4b,iv:TdLjposXXCcKW1dCTkrjejmt5RNQ7xffvjVx3VHKA6I=,tag:xjmYP1PS+rkUr8KEdLwOTQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc1NHbW9xQWlRRGhVYlJS
            WlN1WFhOTzZ0L0plWUxaRjVjZU1yYW1vclRnCmtqdlEwRGVCdUE0c0VMdjZBdW9K
            ZG9Sam1jWDVyZWovaG9haVh2eXhGT00KLS0tIE8ycHRXT0xKT3J3TFJYMFpiN3Qz
            WVV0ellkYkt4NzZYMkxmYmdkTVN5a0UKjFCLWg3pIxNcJvoYZLIv8JZrmZFPaOqS
            4P+VquOH4/4XQbUpJ5dKTTbhLF9v5xasNtUoW5WuVzBa/lSIRUMDng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T07:07:18Z"
    mac: ENC[AES256_GCM,data:N+qrrj3JnYoiFaP/Us5UZhdxgU1B/efdLuu7lZ3rkEP8/xDRjYPVHbXfFRcvtSfVYHcSSZaHMfDtYrWjeya0LKXWfLumZ+LLvMVPB2ZWUpGCy7AmpPeROEUGHo0QpjrlKj6UlgQlNNmQ5UG+3uym+HDqt8Sw/dWQ62hrzEoFJyo=,iv:+uv2gQl5v1cKXMM3aZBzdyey7IWg792oMwA2C2ra4IE=,tag:TojnrxkLCbyaj5TqNxNIRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
