apiVersion: v1
data:
    LD_DB_ENGINE: ENC[AES256_GCM,data:T/E7JI4FmSrcAkhM,iv:VcdTGScSD8uvMQEKy3V6JD+/Rqc9HxGlBeC8fOQwJVk=,tag:0naSQdofbL+cVowZZZWRCg==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:lIZQivN3i5qMiNg0P0Gdhw==,iv:F0cFtvzEogcxDeO3jyQgHCiscQJqFdsLpcyN/o8cKGc=,tag:I/pliBBzvLZYeztv/Wr7AA==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:uKuJPhLlXgYtqhCcw+o9dIbjlCfDnJtA,iv:sbrIgWWk2DARqwXkrthPxFkysTDNtHmeW85e99ZuPr0=,tag:X3jV/B4c2JKY5L4nx8K8EQ==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:qdXZWe6vrVQ=,iv:LNtM16DxybRUK7qP0pSmCZjmcwLdRqGf5YW3jrubnjw=,tag:0mPzLqOXrcosje4LY3ECfw==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:pMluXzUUIoBUTgr4okoOrC+gixo=,iv:eh06szaXulNez57H/qUikX5n7dNmz5GeXBf8TizjzrA=,tag:a1zUqSR/gA7xlHcuYkv81Q==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:WaHE+Vz8Y3s=,iv:+1mNU5dmpBVcGjtOAn7+EYZHnQ1p5Nx12yVqJXga5DY=,tag:0JiFScg9wts93RsPG3VWyw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:CFAE1RcK+tFNGZh9zYuovHq7LSt73af3,iv:s2jQxfukhuuTurl4usEYeubEDzHPxsM1gy3NRUaccxk=,tag:OU8+f6mREsXTr9swRLC4jA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXM3VjV0Y2R1ZqK2ZxaVZO
            S05IQWdKbGMvTnF0UzlJNTJBSlUxZEFWb0hNClFwbnQ5TnZWNG1Jd0I5SG0wTzJ3
            bVJueHJBWWREUUZHT0lzdFhKeWRiOTAKLS0tIFNPS2hWUEd5bytFMnZNaTNPZmVW
            aGoyY2w0eXhBK2RyYjRaT3Zud1p2SlEKOzTGyq6cJt667aemfWIj0+jthOvB81ze
            jT6snrilUPCJuvUeDPPJLL321tGWtZjir6i/LsdVpNBvhrkxhUJsoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T20:23:20Z"
    mac: ENC[AES256_GCM,data:Bp7GG6bk2Cnz937jxSneJd2Cb4wpxSBlDwOtCR5Hulsgsxi3ZjWKDrpV1ttXeyga1kwDslnNoWvk7hQTWRBbG1cVgf8d2G8wSA6agjZzBrsEFir4Rr/mvzt4YDwfkN+zxYeeTnkkZJP//baAzHI5SFUiHhl3CQGks8wqytV+8uw=,iv:YjIdyW0iQ/ZiadYPZNebbIeTkOGCsRDwGsl+8SmEs7A=,tag:PMsse7el26+m9xDeIJ6nTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
