apiVersion: v1
kind: Service
metadata:
  name: ritregistratie
  namespace: ritregistratie
spec:
  type: NodePort
  selector:
    app: ritregistratie
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30288