apiVersion: v1
kind: Secret
metadata:
    name: ejbca-container-env
data:
    TLS_SETUP_ENABLED: ENC[AES256_GCM,data:Xrh0MBSo,iv:Se1j6KEZsWxqt6Jt6Nk0lDahT0atv5WbErjC71YYa10=,tag:aQY0myK5hXWl1ApcxBXbJA==,type:str]
    DATABASE_JDBC_URL: ENC[AES256_GCM,data:XQnoyBELFYO3AkB5KS4dlg2nVyczQjifzwEsoStkUxW5VezkluQuFTE/k4+c18G9MojBGeco6oeL6e85+ASDaAP1Bf5xFnsg1lEEqRaG7Xr/BYZGKVnRog==,iv:oPOAAJdHyXJu+eApd2CuhscluXqcuxU6R3sf2Jbz4Ss=,tag:vlp0axOKhoX/Nw/FITG1Pg==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:EWyzb7k=,iv:NU4MXfvdsXhAxKt8BLa3TDU6xVrF1zug1mYgya/NM6E=,tag:oqKMACb+VF8WcYoQWrb1vQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:swz866uTS6u/AOL80bXqWgdZqWbOU6bPgsCe7o9r,iv:J5GD2n2kGyZjuy2WTZ+6rvswJCSk7hTxQCTgt7OTAh0=,tag:COJgjmzqalhesoR2meSlzA==,type:str]
    PASSWORD_ENCRYPTION_KEY: ENC[AES256_GCM,data:AF1jASHY1hrD8k7YVfWoZwrK5oWwOP6kDAiopdEfmLyqLH+5ySy+iiRY,iv:SFrdrQg1deti/2WdzKty1DxCKxyyN5RKmmEwaIbcNDI=,tag:YpcBRJvdy/ODMp5a59H5rg==,type:str]
    CA_KEYSTOREPASS: ENC[AES256_GCM,data:SWgx1R6rIfbaUOI+mBbw+41wIDKgYYj5Apux84VTqzk=,iv:jl+rDCEBABX1fQKfIJGZ3NZOq5Y4znApkiW+d2UQXYw=,tag:fmlCrdmkqTp2DR99iDdjNg==,type:str]
    EJBCA_CLI_DEFAULTPASSWORD: ENC[AES256_GCM,data:prad+Jc3bm5GyJHYY4zwyMbXvEmUy7OehpG7GNnKNQ==,iv:CUxonBazxXhlUl1yGlq41X2fPcDa0VgU8boD4LFW9oo=,tag:Uhbn7oIhN72zoSzmRzbpaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR2tiYTh0emU3cEQ5UHlR
            QTVkTjgzdGRxMkRwTkwxVUR2aTdYYzBRTzBnClcweWhsSUZrbUY1UHZoTzFPQ0Q5
            cjVPRUI0Nml1UE5YTXdhR2s2d1pubzgKLS0tICtqaHl3NER2MUlUTEFqM2NQeENZ
            K1ZDaDdGT3VSQllROFJwRm9HeEs5ZU0KmZORRg3wAXdywVRP+p1XFjQYfxQv8CX2
            rYAASW1EYCx2oDk5HVsO4GoILhLl0lRrjgPObX3Sxuj4w9hs9sA04g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T07:05:46Z"
    mac: ENC[AES256_GCM,data:JK8AdKzQ5oNFk1LZBORcMxYiOI0GlvCiK0whAyT1wriLV1cZ/RRDbHIWcsaNX5z8EX5qsMaL4DWmtnnW4jG179CkpNqDYIBezao9FSszjK8B1QsIB6zwIM564z5cLpac9lti8cH1IYzrUmW0T3X8bflTdrL0xE4rk6QXzvWmNsU=,iv:OP8KxblJWMR2aMDDlxWUJucUptGsG4rA2EXuXTDDjPs=,tag:5ZFV/IQd7pZIzVqZY5fYmA==,type:str]
    version: 3.13.3
