apiVersion: v1
kind: Secret
metadata:
    name: ejbca-container-env
data:
    TLS_SETUP_ENABLED: ENC[AES256_GCM,data:PKeFTFQoVJY=,iv:nut6i216lE2LVYhdcScXWkPCivF0O+UcLtb6HVHdBSs=,tag:HerUMpaWT5fY8ZYZYMXtrQ==,type:str]
    DATABASE_JDBC_URL: ENC[AES256_GCM,data:BJgD8USN9xI24vG5SAgeWPlLiteJsoBCvGVmKdySQlK6n1/o2Monpn2zZV0U4cMTTOpTfL/DV1B5Ku1jfqBOPLvUCpWjfNvdTInZRwIOxhgOe12tUlGMUiuIk4ZnHD5kVn8RbiY9/FOIihgHslirv81XSq7vNmdL,iv:kjgCwAeqeovy5Mj721cHvTneRvA3tcNMla1ZdjiOcMs=,tag:d7RFlQO8AsQkD3V8Bd2pqw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:GWL2OpWoPzk=,iv:0SWr5pgHHlIX4knfzsSs7dnA1Ljd+x5fP5y9Cj4o47U=,tag:yojd5C5WaMrZEHqwT8R3+Q==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:yJ8pkfKl2oBMSNsqvkQssHkMgoR1D1uAugt1LmLmsjZXzVNtz7daaA==,iv:CRX5NC1KvdfbdoSOCopYpOETUbk0ZIN1AZBG8Q02kqI=,tag:nJ0dBpZFB5roQzmT15Q9rQ==,type:str]
    PASSWORD_ENCRYPTION_KEY: ENC[AES256_GCM,data:oLZeHB8WwnhOwY0UXVMQTTVeBNn0676R7V1ZPxdlsizTd7DWnNd/5FgWaKQNTffBPg88h2VF5Lo=,iv:/2o+yADQY2zUR3tc2S8+KROp0frvRls1uo2tfvBBREY=,tag:qZJtwJCWt1cXz6XuBYdMLw==,type:str]
    CA_KEYSTOREPASS: ENC[AES256_GCM,data:pBUBo+fGyqgaFZj5v37aj6Y5MDfotz6MS0IM48LmBH9J4XqhRriSFbgxXeY=,iv:8U8xqBb2zqjzIgg7Gf3l7vsZrh3Rf4alR6Cs2V4Yn2g=,tag:2it0AgHUZUAIm2wHSp2j3A==,type:str]
    EJBCA_CLI_DEFAULTPASSWORD: ENC[AES256_GCM,data:xPWvScfR2E/B7m5aWw+kJ+vVkyYagxRbMxPq7J5fdymPcW5Fp3HnguSdB+4=,iv:0vGDXpcq1vBnggpyQz8vYk5V5Q/B2Y/ajQSItbvBIEo=,tag:TahITCdlr7flYkIlTxhsQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU2hLckVQT0dPUUt4MSs5
            VmxHTVl1RmJWeDBTcW5mTnFoOWpxWDFrR3pjCkx0UkxqVVZDcXRQSWNDZVlsbUhT
            SFltYmxhSWRDZlYrTEY2VVdITHpOMTQKLS0tIHpYWDFUTkNmRkZ0cWlBSlo5RTM0
            SzJFSDRyVmlDR1FraGdUajZIL3Irc1kK54XCDfAVsfxPBhk3SsHfshjDMv5o2Isc
            F6RsFe59o1JrrDurpftIVNqYIX3W3brTntEz6twjoFvU3Cbpw1O+eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T08:03:45Z"
    mac: ENC[AES256_GCM,data:zVtJOCigGK/Gkf3DpyIXfMr27h6iNGE9cqaE8oqhoTJ2NUYpSdcxtKcOFzQMx5s/P6Alww84wDBvzFgsneCL8ibBLMf3KqVimHru0DbXoB0Prbsly7Yy457zt4dxDETiUk+1nBnDyLON9b/ZnRjxaLq8Q5fCTFaBvVWn318/Hik=,iv:0KYYZJ1npYZ0dBbbm9la1dFGBjInBqNb3sPk+T0J5qQ=,tag:jNttRZ/8BhetulCbr/gB3A==,type:str]
    version: 3.13.3
