apiVersion: v1
kind: Secret
metadata:
    name: timing-tower-db
    namespace: timing-tower
type: Opaque
stringData:
    DATABASE_URL: postgresql://timingtower:Laxative1-Falcon9@192.168.2.24:30432/timing_tower