apiVersion: v1
kind: Secret
metadata:
    name: timing-tower-db
    namespace: timing-tower
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:N8jvY+EHSydZwV9Zhv2ZOn1OLmskSpiFRVohMpZqWdyQ4MaHHBvU4n2niQNZ3QbxIw7s1QV9xFaHLR6Ptbq4M+UhCL7xEl6e9GE=,iv:mHVJfoXiEuJecqsmzIUaSLetmcizqYZIvgteO+QtJvo=,tag:DiyKr+oHqoI92iCw/gp2gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWREx5WTdBVDlWblFWa1FI
            VkFDNDUxUGJYVkUzWk5hdm85bnFMOUNLeUhjClNyVzdLOUE0YmV3elhtWE9xeHhR
            bzJMNVlIb2p5Qi8vRXJuanN1dVA2aG8KLS0tIDRWbXRidTd3VWVqSlAzTG5PYWdK
            bnVEQStDU2s5eXpGckl5V1pKb2NreHMKij2a1P4wZZ7JaFxb0Y0zHvNWwcHVgeru
            JyOZD/uivLNLI5PDpExSI7cCAhz5Bx3xQ/+BWTZP028D3UBMERbn1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T19:51:14Z"
    mac: ENC[AES256_GCM,data:FxnC7gMAl0S+3N1klE7mpQ6vtRS73j2zeopKJO+iLK/RlH3gn3d3jcM8ACiT15ez4me07KfETlGM7gzXHRTYSarBKUSCX3W1JtIZZRIl5cHlWutg/FKdSaaMfKbU2lLSqAK1E6CTa2u/H+acXwBZqjO5xRZ5pdHJDJxex+iRTp0=,iv:rvjT9KXOREZkwXgIy0SwA75MznbKcfxVsg579QWT+Ow=,tag:0IbCrA12jGRcdXW1xdPlQQ==,type:str]
    version: 3.13.3
