apiVersion: v1
kind: Secret
metadata:
    name: ontime-db
    namespace: ontime
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:O0SpCLVsCkzz7/OnHPEWVYbR9GgU+dHzl/YNH+st37z76SSG5ixiFNBXy4+ZZSYh2l7PpOBsugU5i5bRZjmoPNEmlntM9EtF+eiFoKYT9iABJEbxIb5MmW0Itht06I80MAu+6Q==,iv:XqrIBp0KYuEeLE4oqkYnvJ42NxjxsD1LWXpoKvooFLk=,tag:uf+YrN8fLY3EMsIqyR30nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR0ZMV2tMc0o0RjZjaHRT
            dGdSNHA4d1FCZ2J5S0x1bStBTFBsM0NsVm5rCi9OY1pVOG80MVAxWHlsbWdkNC9G
            NlF2aE9YSzVlN1F5RjRXUnhPUHlTaVUKLS0tIFNSaUE3YXZHVnYwSmt3ZzNiQ1lv
            VGRwUU80N1JSR1BzY0dCT3MxdXBtTGcK9bHwLOKSAUKC4y3KMDIyPXTkjPj64iJz
            APWVTjTfd+6oEoaYlMfTmVpfUSZgvGwS7vPXoJt7P6hNdtcOeHIlcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T19:36:47Z"
    mac: ENC[AES256_GCM,data:9RG7B4ElA5OfqUaxKa0ydVWRtfODCeIKsElDtdOPVqkmOq2EayuqYL1ZOGstjENUsilz3vqDER2TMxcnOTZxblFWliCtyc3F8aYQvzJnQ0jUoh4J/PgTrR0i7fSIzxPqPSu6qVlfLI4d0vS54NMQ0A0K1rz0VvEzuP5gjPNxl7A=,iv:xdJdvknNlxOF1JaLFG+QWK+LZgZHd4ts+O8rqzfS8Rs=,tag:qvfp4OPyZJHP21o2s3gv/g==,type:str]
    version: 3.13.3
