apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:AmQ5hky7/Kx2yPO1VEgGuvxCZ00xW530nDsuYbUUxIeXol8rLK6I4xF/CXtt8ZCxwRNGlb4I3wI=,iv:htfLrT1siMZ6zXg9wAtr4ahKpF32KDsMuuZPuWC8m0A=,tag:yT7gFDgFuF8ZSdri/7//Cw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMlBhZzJ0Y0JNV2ppM2ZU
            dmhlKzdCSDhPMzlSaDhUWUtrUVkvNE9UaFZrClEwNS9ZSUcrcXlSMzIzRTJlRnIw
            L1QyVmxKTFF3WExFV2FuOGJjaVBlK0UKLS0tIHZVWG1WQ0pCb0E4cU54d0VCcGpn
            L3R4cEtRSUV3ZWRYeEhNSEtmb1Z5S0EK8OD1jXqj+jsKmVOxllcLCNMA4hRimEbo
            MEDN2hQs4pjWQtdcDOTyZkL31WFs5CtoChtgpjs3C7k2qwLgreMgbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q8xgjrfpg3prhup4c05dzk788tr3u799w8mh5khue4umt2jmulqmgmvwv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T15:03:14Z"
    mac: ENC[AES256_GCM,data:Vvwaiy8hQkJVAzHlgzp0uqMRSgvmin/XQn5T3SS1YzsDEpBs7POfFa+OF8OjjnIqY+tfYIKRRRxDbd8m1dzsbxRFddnTKFVnfnwZr9cANxPX+OcOIXu4n82/X9MWtZLFaG9LUSRSoN7xa14/bpWvqRuFTvDwgRKtqqXyJ2jK0Sc=,iv:kYyBtSLdO7rKeJYxJHt5LFS1vcVX94rVNRH6mQobBS0=,tag:uSfCWlvXreKJb5eNg9JhCA==,type:str]
    version: 3.13.1
